name:                intellegere
version:             0.1.0.0
github:              "hhefesto/intellegere"
license:             BSD3
author:              "hhefesto"
maintainer:          "hhefesto@rdataa.com"
copyright:           "BSD-3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hhefesto/intellegere#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  intellegere-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intellegere

tests:
  intellegere-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - intellegere
